---
abstract: 'Module for simple configure file parsing.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.16
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Dot
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.03
  Config::Utils: 0.03
  Error::Pure: 0.16
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Config-Dot
  homepage: https://github.com/tupinek/Config-Dot
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: git://github.com/tupinek/Config-Dot
version: 0.06
